FORMAT: 1A

# utm-jobposts

The jobposts API allows umantis to query the status of jobposts.

## JobPosts Publications [/jobposts/{umantis_customer_id}?page={page}&limit={limit}]

+ Request

    + Headers
    
        Authorization : API-KEY deadbeef

    + Parameters
        + umantis_customer_id: 1 (number, required) - the contents of the umantis-customer-id tag
        + page: 0 (number, optional) - in order not to overload the network we go page by page
        + limit: 10 (number, optional) - number of items on a page

### List JobPosts for an umantis customer [GET]

+ Response 200 (application/hal+json)
    + Body  
    + Attributes
        + _embedded
            + jobposts (array[JobPost])
        + page (Page)
        + _links
            + self: /jobposts/1054 (string)
            + next: /jobposts/1054?page=1&limit=10 (string)

#Data Structures

## JobPost
+ umantis_job_id: 1 (number, required) - the contents of the umantis-job-id tag
+ jobtitle: Java rockstar for talent management (string, required) - the contents of the name tag
+ jobboard_publications (array[Jobboard Publication])

## Jobboard Publication
+ job_board_name: Monster (string, required) - the name of the job board
+ status (enum, required) - the status of the publication on the job board
    + Published
    + Not published
+ start_time: `2015-09-01T12:00:00+01:00` (string, optional) - the publication is visible from
+ end_time: `2015-10-01T12:00:00+01:00` (string, optional) - the publication is visible until
+ modified: `2015-08-24T12:00:00+01:00` (string, optional) - last modification
+ cost_value: 1054 (number, optional) - the cost of the publication on the job board 
+ cost_currency: EUR (string, optional) - the currency of cost of the publication on the job board, ISO code
+ localizations (array[Localization]) - list of language variants of the job post

## Localization
+ job_title: Java Engineer needed in Eastern-Switzerland area (string, required) - localized job title
+ locale: en (string, required) - ISO language code

## Page
+ page: 0 (number, required) - we are on this page
+ limit: 10 (number, required) - this is how many elements were requested and at most served
+ total_elements: 100 (number, required) - this many elements are available for this customer
+ total_pages: 10 (number, required) - this many pages are available for this customer