FORMAT: 1A

# utm-multiposter Solique

The jobposts API enables Haufe-umantis partner (Solique) to update jobposts information.

## JobPosts Publications [/public/multiposters/solique]

+ Attributes (JobPost)

### Update JobPost details  [PUT /public/multiposters/solique/vacancies/{umantis_job_id}]

Updates a specific job for an umantis customer.


Invalid Requests:
| Cause                        | Response code     |
|------------------------------|-------------------|
| Invalid SOLIQUE-API-KEY      | 403               |
| Invalid message format       | 406               |


+ Parameters
    + umantis_job_id: 2 (number, required) - the id sent in field umantis-job-id in the XML document

+ Request
    + Headers
    
            Authorization: SOLIQUE-API-KEY deadbeef
    + Body
    + Attributes
        + available_until: `2015-09-01T12:00:00+01:00` (string, required)
        + _embedded
            + jobpost (JobPost, required)

+ Response 200

+ Response 403

+ Response 406

### List JobPost details [GET /multiposters/solique/vacancies/{umantis_job_id}]

Lists all jobposts of a position for an umantis customer. atm. this API is not public!

+ Parameters
    + umantis_job_id: 2 (number, required) - the id sent in field umantis-job-id in the XML document+ Request
    + Headers
    
            Authorization : auth-token deadbeef


+ Response 200 (application/hal+json)
    + Body  
    + Attributes
        + _embedded
            + jobposts (array[JobPost])
                

+ Response 403

#Data Structures

## JobPost
+ umantis_job_id: 1 (number, optional) - the contents of the umantis-job-id tag
+ jobtitle: Java rockstar for talent management (string, required) - the contents of the name tag
+ jobboard_publications (array[Jobboard Publication])

## Jobboard Publication
+ job_board_id: 1a (string, required) - the unique channel ID
+ job_board_name: Monster (string, required) - the name of the job board
+ status (enum, required) - the status of the publication on the job board
    + Published
    + Not published
    + Updated
+ start_time: `2015-09-01T12:00:00+01:00` (string, optional) - the publication is visible from
+ end_time: `2015-10-01T12:00:00+01:00` (string, optional) - the publication is visible until
+ modified: `2015-08-24T12:00:00+01:00` (string, optional) - last modification
+ cost_value: 1054 (number, optional) - the cost of the publication on the job board 
+ cost_currency: EUR (string, optional) - the currency of cost of the publication on the job board, ISO code
+ order_placement_date: `2015-08-24T12:00:00+01:00` (string, optional) - date when publication order was created – “Processed on”
+ order_placement_person: (string, optional) - name of person that created the publication order – at Solique it’s: “Processed by”
+ order_number: 9999 (number, optional) - ID of publication order - at Solique it’s: “Order number”
+ order_rate: string (string, optional) - rate for a single order on a specific media – at Solique it’s: “Rate”
+ contingent: string (string, optional) - number of job-publications used, compared to the total number of job-publications available/bought on a specific media
+ localizations (array[Localization]) - list of language variants of the job post
+ _links
    + deactivate
        + href: http://solique.ch/.... - an URL that points deactivation page/URL of the job post
        method: POST, must have a Authorization: Basic header with the job owners username and password

## Localization
+ job_title: Java Engineer needed in Eastern-Switzerland area (string, required) - localized job title
+ job_description: Lorem ipsum dolor sit amet consetetur sadipscing elitr ... - desciption of the job
+ job_description_parts (array[Job Description Part]) - a list of job description segments in the format of key-value pairs (only specified, but ignored for the moment)
+ locale: en (string, required) - ISO language code
+ _links
    + job_url
        + href: http://solique.ch/.... - an URL that points to the language specific job page in the solique system

## Page
+ page: 0 (number, required) - we are on this page
+ page_size: 50 (number, required) - this is how many elements were requested and at most served
+ total_count: 100 (number, required) - this many elements are available for this customer
+ total_pages: 2 (number, required) - this many pages are available for this customer

## Job Description Part
+ key: Responsiblities (string, required) - the key for the job description segment
+ value: Lorem ipsum dolor sit amet con ... - the text segment of the job description